elasticsearch:
  image: bitergia/elasticsearch:6.1.0
  # image: bitergia/elasticsearch:5.6.0
  command: /elasticsearch/bin/elasticsearch -E network.bind_host=0.0.0.0
  # image: elasticsearch:2.2
  # command: elasticsearch -Des.network.bind_host=0.0.0.0 -Dhttp.max_content_length=2000m
  ports:
    - "9200:9200"
  environment:
    - ES_JAVA_OPTS=-Xms2g -Xmx2g

kibiter:
  image: bitergia/kibiter:6.1.0
  # image: bitergia/kibiter:5.6.0
  # image: bitergia/kibiter:4.4.1
  links:
    - elasticsearch
  ports:
   - "5601:5601"
  environment:
    - ELASTICSEARCH_USER=bitergia
    - ELASTICSEARCH_PASSWORD=bitergia
    - PROJECT_NAME=Test20
    - NODE_OPTIONS=--max-old-space-size=1200

redis:
  image: redis:latest
  command: redis-server --save "" --appendonly no
  ports:
        - 6379:6379

arthur:
  image: acsdocker/arthur
  links:
        - redis
  ports:
        - 8080:8080

mordred:
  image: bitergia/mordred:elasticgirl.29
  links:
    - arthur
    - bestiary
    - elasticsearch
    - kibiter
    - mariadb
    - redis
  volumes:
    - .:/home/bitergia/conf
    - ./logs:/home/bitergia/logs
  #  - ./stage-mordred:/home/grimoirelab/stage

mariadb:
    image: mariadb:10.0
    command: --wait_timeout=2592000 --interactive_timeout=2592000 --max_connections=300
    environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
        - 3306:3306

bestiary:
  image: acsdocker/bestiary
  links:
        - mariadb
  ports:
        - 8000:8000

hatstall:
  image: acsdocker/hatstall
  links:
        - mariadb
  ports:
        - 8001:8000
